### ISSUE TITLE
Cannot lifecycle ignore write_capacity and read_capacity

### ISSUE THREAD

**Issue by bataras** [terraform-aws-modules/terraform-aws-dynamodb-table#17] opened 2020-07-16 01:25 UTC
Cannot set the lifecycle field for the underlying aws_dynamodb_table. When the table has scaled up, running terraform apply tries to reset the write_capacity to its base value

**Comment by max-rocket-internet** [comment] 2020-07-16 10:50
Duplicate of https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/issues/14

**Closed by max-rocket-internet** 2020-07-16 10:50 UTC
